export const BODY_COLUMN_INDENT = 2100;
export const BODY_COLUMN_RIGHT_INDENT = 350;
export const CONTINUATION_RULE_INDENT = 1725;
export const WORD_LINE_MULTIPLE_108 = 259;
export const WORD_LINE_MULTIPLE_115 = 276;
export const WORD_INDENT_002_CM = 11;

export const APPENDIX_COLUMN_WIDTHS = [5, 42, 42, 11] as const;
export const APPENDIX_HEADER_FILL = "D9D9D9";
export const TABLE_HEADER_FILL = APPENDIX_HEADER_FILL;
export const DEVELOPMENT_COLUMN_WIDTHS = [8, 24, 68] as const;
